#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate embedded Rust declarations from the approved Gate-A/B artifacts."""

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
PARAMETER_SHA = "13f0eaf541919a1447b9d3c58e6d57eb77ffab94ebe37539c70301d6fddcfaa0"
VECTOR_SHA = "4dbbd93f5814f4e676b8007b13973037a7924872d46d328cdaeb314cd3190e82"


def bound_json(path, digest):
    raw = path.read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        raise RuntimeError(f"approved artifact hash mismatch: {path}")
    return json.loads(raw)


def generate():
    data = bound_json(ROOT / "provenance/phase-a/2026-09-09/parameter/ed301-v2.json", PARAMETER_SHA)
    vectors = bound_json(ROOT / "vectors/ed301-eddsa-v2.json", VECTOR_SHA)
    source = ROOT / "reference/ed301_curve.py"
    if hashlib.sha256(source.read_bytes()).hexdigest() != "b6e5f7d1788965f3efb40a9057b7d830b411ed806c82b765f0c2e47ee34c893f":
        raise RuntimeError("Gate-B curve reference hash mismatch")
    sys.path.insert(0, str(ROOT / "reference"))
    import ed301_curve as c

    p, q = int(data["field"]["p_decimal"]), int(data["group"]["q_decimal"])
    a, d = int(data["edwards"]["a_decimal"]), int(data["edwards"]["d_signed"])
    inv = int(data["field"]["inversion_exponent"])
    sqrt = int(data["field"]["square_root_exponent"])
    ratio = int(data["field"]["square_root_ratio_exponent"])
    if (inv, sqrt, ratio) != (p - 2, (p + 1) // 4, (p - 3) // 4) or d != -301:
        raise RuntimeError("unexpected approved field/exponent profile")
    fold = (1 << data["field"]["bit_length"]) - p
    subtrahend = p & ((1 << 64) - 1)
    power = fold + subtrahend
    if power & (power - 1):
        raise RuntimeError("field is not in the approved two-term folding family")
    fold_exponent = power.bit_length() - 1
    if fold_exponent != 89 or subtrahend != 907 or a.bit_length() != 36:
        raise RuntimeError("unexpected approved sparse-field profile")

    out = ["// SPDX-License-Identifier: Apache-2.0",
           "// Generated by phase-c/tools/generate_rust_parameters.py; do not edit.",
           f"// Gate-A SHA-256: {PARAMETER_SHA}", f"// Gate-B vector SHA-256: {VECTOR_SHA}",
           "// No parameter file is accessed by the compiled implementation."]

    def integer(name, value, ty="u64", test=False):
        if test:
            out.append("#[cfg(test)]")
        out.append(f"pub(crate) const {name}: {ty} = {value};")

    def hex_constant(name, value, test=False):
        if test:
            out.append("#[cfg(test)]")
        out.append(f'pub(crate) const {name}: &str = "{value:080x}";')

    def array(name, values, ty, render, cfg=None):
        if cfg:
            out.append(f"#[cfg({cfg})]")
        out.append(f"pub(crate) const {name}: [{ty}; {len(values)}] = [")
        out.extend("    " + render(v) + "," for v in values)
        out.append("];")

    def words(name, value, cfg=None):
        array(name, [(value >> (64 * i)) & ((1 << 64) - 1) for i in range(5)], "u64", lambda v: f"0x{v:016x}", cfg)

    def encoded(name, value, cfg="test"):
        array(name, list(value), "u8", lambda v: f"0x{v:02x}", cfg)

    integer("EDWARDS_A", a)
    integer("EDWARDS_D", d, "i16")
    integer("EDWARDS_D_MAGNITUDE", -d)
    integer("SMALL_MULTIPLIER_BITS", a.bit_length(), "u32")
    integer("MAX_SMALL_MULTIPLIER", (1 << a.bit_length()) - 1)
    integer("FOLD_SUBTRAHEND", subtrahend)
    integer("FOLD_SHIFT", fold_exponent - 64, "u32")
    integer("FOLD_LOW", fold & ((1 << 64) - 1))
    integer("FOLD_HIGH", fold >> 64)
    for name, value in (("FIELD_MODULUS_HEX", p), ("SCALAR_MODULUS_HEX", q),
                        ("SQRT_EXPONENT_HEX", sqrt), ("SQRT_RATIO_EXPONENT_HEX", ratio)):
        hex_constant(name, value)
    hex_constant("RADIX_304_REDUCED_HEX", pow(2, 304, q), test=True)
    for name, value in (("MODULUS_WORDS", p), ("TWO_P_WORDS", 2 * p),
                        ("INVERSION_WORDS", inv), ("SQRT_RATIO_WORDS", ratio),
                        ("BASE_X_WORDS", c.G[0]), ("BASE_Y_WORDS", c.G[1]),
                        ("BASE_T_WORDS", c.G[0] * c.G[1] % p)):
        words(name, value)
    encoded("BASE_ENCODING", c.G_ENCODING)
    encoded("BASE_U_ENCODING", bytes.fromhex(data["basepoint"]["G_montgomery_u_little_endian_hex"]))
    encoded("PRIME_ORDER_ENCODING", q.to_bytes(38, "little"))
    encoded("FIELD_MODULUS_ENCODING", p.to_bytes(38, "little"))
    encoded("FOLD_ENCODING", fold.to_bytes(38, "little"))
    words("SQRT_25_WORDS", pow(25, sqrt, p), "test")
    words("SQRT_49_WORDS", pow(49, sqrt, p), "test")
    nonpoint = next(v for v in vectors["point_decoding"] if v["id"] == "nonsquare-x")
    encoded("NONPOINT_ENCODING", bytes.fromhex(nonpoint["encoded_hex"]))
    value, position, wnaf = q, 0, []
    while value:
        if value & 1:
            digit = value & 255
            if digit >= 128:
                digit -= 256
            value -= digit
            wnaf.append((position, digit))
        value >>= 1
        position += 1
    wnaf.reverse()
    if sum(digit * (1 << position) for position, digit in wnaf) != q:
        raise RuntimeError("wNAF reconstruction failed")
    array("PRIME_ORDER_WNAF8_DESC", wnaf, "(u16, i8)", lambda v: f"({v[0]}, {v[1]})")
    array("PRIME_ORDER_SET_BITS_DESC", [i for i in range(q.bit_length() - 1, -1, -1) if (q >> i) & 1],
          "u16", str, 'any(test, feature = "sign-self-verify")')
    trace = vectors["signing"][0]["trace"]
    for name, key in (("TEST_PRUNED_SECRET", "pruned_secret_scalar"), ("TEST_PUBLIC_ENCODING", "public_key"),
                      ("TEST_NONCE_SCALAR", "nonce_scalar"), ("TEST_COMMITMENT_ENCODING", "commitment")):
        encoded(name, bytes.fromhex(trace[key]))
    for name, point in (("MULTIPLE_12345_ENCODING", c.scalar_multiply(12345, c.G)),
                        ("ORDER_TWO_ENCODING", c.ORDER_2), ("ORDER_FOUR_ENCODING", c.ORDER_4),
                        ("MIXED_ORDER_TWO_ENCODING", c.point_add(c.G, c.ORDER_2)),
                        ("MIXED_ORDER_FOUR_ENCODING", c.point_add(c.G, c.ORDER_4))):
        encoded(name, c.encode_point(point))
    return subprocess.run(["/usr/bin/rustfmt", "--edition=2024", "--emit=stdout"],
                          input="\n".join(out) + "\n", text=True, capture_output=True,
                          check=True).stdout


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", type=Path)
    args = parser.parse_args()
    content = generate()
    if args.check:
        if args.check.read_text() != content:
            raise SystemExit("FAIL: embedded Rust parameters differ")
        print("PASS: embedded Rust parameters reproduce Gate A/B")
    else:
        print(content, end="")
