[workspace]

[package]
name = "x301-core-timing-adapter"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
x301-core = { path = "../../rust/crates/x301" }
zeroize = "=1.9.0"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "unwind"
overflow-checks = true
