#!/usr/bin/env python3
"""Derive direct dependency roles and retained-only vendor names from Cargo files."""
import argparse
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[1]
MANIFESTS = (
    "rust/crates/ed301-eddsa/Cargo.toml", "rust/crates/x301/Cargo.toml",
    "provider/crates/ed301-eddsa-provider/Cargo.toml", "provider/crates/x301-provider/Cargo.toml",
    "rust/secret-taint/valgrind-client/Cargo.toml",
)
LOCKS = ("rust/Cargo.lock", "rust/crates/x301/Cargo.lock", "provider/Cargo.lock")


def read(path):
    return tomllib.loads(path.read_text())


def render():
    lines = ["# Cargo dependency inventory", "",
             "Generated by `tools/check_dependency_inventory.py` from the active manifests",
             "and three lockfiles. Roles below describe direct Cargo edges, not DSO contents.",
             "Target-specific and optional dependencies still require feature/platform selection.", "",
             "| Consumer | Dependency | Role | Optional |",
             "| --- | --- | --- | --- |"]
    for filename in MANIFESTS:
        manifest = read(ROOT / filename)
        consumer = manifest["package"]["name"]
        for section, role in (("dependencies", "normal"), ("build-dependencies", "build"),
                              ("dev-dependencies", "test")):
            for name, entry in sorted(manifest.get(section, {}).items()):
                optional = isinstance(entry, dict) and entry.get("optional", False)
                lines.append(f"| `{consumer}` | `{name}` | {role} | {'yes' if optional else 'no'} |")
    locked = {p["name"] for filename in LOCKS for p in read(ROOT / filename)["package"]}
    vendor = {read(path)["package"]["name"] for path in (ROOT / "rust/vendor").glob("*/Cargo.toml")}
    retained = sorted(vendor - locked)
    lines += ["", "Vendor sources absent from all three active lockfiles: "
              + ", ".join(f"`{name}`" for name in retained) + ".", "",
              "These retained sources keep their licenses and provenance. `cc` builds the",
              "ordinary provider C shims; it is not itself linked into their DSOs. Provider",
              "randomness comes from OpenSSL, not a direct `getrandom` dependency.", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if (ROOT / "docs/DEPENDENCIES.md").read_text() != content:
            raise SystemExit("dependency inventory differs from Cargo inputs")
        print("dependency inventory: PASS")
    else:
        print(content, end="")
